'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';
import type {MenuItem} from '@/data/menu';

type Lang='en'|'ar';
type Ctx={lang:Lang;setLang:(l:Lang)=>void;t:(key:string)=>string;itemName:(item:MenuItem)=>string;itemDescription:(item:MenuItem)=>string;choice:(label:string)=>string;category:(label:string)=>string};

const en:Record<string,string>={
 'nav.home':'Home','nav.menu':'Menu','nav.burgers':'Our Burgers','nav.sandwiches':'Sandwiches','nav.sides':'Sides','nav.drinks':'Drinks','nav.about':'About','nav.contact':'Contact','nav.order':'ORDER NOW',
 'hero.kicker':'SIGNATURE EXPERIENCE','hero.title1':'BUILT','hero.title2':'TO CRAVE','hero.copy':'Eight real layers. One epic burger. Scroll down to see it come to life.','hero.scroll':'SCROLL',
 'pack.kicker':'THE ULTIMATE COMBO','pack.title1':'PACKED','pack.title2':'PERFECTLY','pack.copy':'Freshly made. Perfectly packed. Made for one purpose. You.','pack.cta':'BUILD YOUR ORDER','pack.ready':'READY TO GO','pack.closed':'Packed. Sealed. RiWebs.',
 'home.signature':'SIGNATURE BURGERS','home.choose':'Choose your\nmain character.','home.view':'VIEW ALL BURGERS →','home.lane':'PICK YOUR LANE','home.more':'More than\none craving.','home.explore':'EXPLORE FULL MENU →','home.manifestoTag':'RIWEBS / GOOD FOOD / GOOD TIMES','home.manifesto':'THE KIND OF BURGER\nYOU THINK ABOUT\nON THE WAY HOME.','home.exploreCard':'EXPLORE',
 'cat.burgers':'BURGERS','cat.sandwiches':'SANDWICHES','cat.sides':'SIDES','cat.drinks':'DRINKS','cat.burgersCopy':'Big stacks. Bigger craving.','cat.sandwichesCopy':'Grab it. Bite it. Repeat.','cat.sidesCopy':'The extras are not optional.','cat.drinksCopy':'Cold enough for the next bite.',
 'page.menu.kicker':'FULL MENU','page.menu.title':'Pick your craving.','page.menu.copy':'Curated burgers, complete meals, crispy sides, cold drinks and the sauces that make the last fry worth fighting for.',
 'page.burgers.kicker':'OUR BURGERS','page.burgers.title':'Stacked with intent.','page.burgers.copy':'Every burger is built around texture: a toasted bun, bright greens, a strong center and enough sauce to make it unmistakably RiWebs.',
 'page.sandwiches.kicker':'SANDWICHES','page.sandwiches.title':'Built to grab. Hard to put down.','page.sandwiches.copy':'RiWebs sandwiches, each with its own texture, sauce and attitude.',
 'page.sides.kicker':'SIDES & SAUCES','page.sides.title':'The extras earn their place.','page.sides.copy':'Golden fries, coleslaw and the sauces that finish the order — ketchup, ranch, mayonnaise, mustard and BBQ.',
 'page.drinks.kicker':'DRINKS','page.drinks.title':'Cold enough to reset the bite.','page.drinks.copy':'Cold drinks and energy drinks, with flavour choices where available.',
 'page.about.kicker':'OUR STORY','page.about.title':'A burger brand with its own point of view.','page.about.copy':'RiWebs is built around one simple idea: familiar food can still feel designed, thoughtful and worth getting excited about.','about.why':'WHY RIWEBS','about.head':'Good food.\nGood design.\nNo shortcuts.','about.copy':'From the stack to the packaging, every touchpoint carries the same identity. Warm colors. Big appetite. Clean details. A restaurant experience that looks as considered as it tastes.','about.v1':'CRUNCH FIRST','about.v1c':'Texture matters as much as flavor.','about.v2':'BUILT FRESH','about.v2c':'Every layer earns its place.','about.v3':'MAKE IT RIWEBS','about.v3c':'A recognizable experience from box to last bite.',
 'page.contact.kicker':'CONTACT','page.contact.title':'Come hungry.','page.contact.copy':'Questions, feedback or just trying to decide what to eat? RiWebs is here.','contact.location':'LOCATION','contact.hours':'OPENING HOURS','contact.daily':'Daily','contact.city':'Cairo','contact.country':'Egypt','contact.instagram':'INSTAGRAM','contact.facebook':'FACEBOOK','contact.tiktok':'TIKTOK','contact.visit':'VISIT','contact.map':'RIWEBS RESTAURANT','contact.maploc':'CAIRO, EGYPT',
 'cart.title':'YOUR ORDER','cart.cart':'Cart','cart.empty':'Your cart is waiting for something delicious.','cart.total':'Total','cart.confirm':'CONFIRM ORDER ON WHATSAPP','cart.note':'Your selected items, quantities and options will be sent automatically to RiWebs on WhatsApp for confirmation.','cart.clear':'Clear order','cart.standard':'Standard',
 'custom.size':'SIZE','custom.type':'TYPE / FLAVOUR','custom.extras':'EXTRAS','custom.add':'ADD TO ORDER','card.from':'FROM EGP','filter.all':'All','filter.burgers':'Burgers','filter.sandwiches':'Sandwiches','filter.meals':'Meals','filter.sides':'Sides','filter.drinks':'Drinks','filter.sauces':'Sauces',
 'footer.tag':'Burgers, fries and good times — served with a little more craft.','footer.explore':'EXPLORE','footer.visit':'VISIT','footer.follow':'FOLLOW · VISIT','footer.daily':'Daily','footer.menu':'Menu','footer.burgers':'Our Burgers','footer.sides':'Sides & Sauces','footer.drinks':'Drinks','footer.privacy':'PRIVACY','footer.terms':'TERMS','footer.order':'ORDER FROM RIWEBS',
};
const ar:Record<string,string>={
 'nav.home':'الرئيسية','nav.menu':'المنيو','nav.burgers':'البرجر','nav.sandwiches':'الساندوتشات','nav.sides':'السايدز','nav.drinks':'المشروبات','nav.about':'عن RiWebs','nav.contact':'تواصل معنا','nav.order':'اطلب الآن',
 'hero.kicker':'تجربة RiWebs المميزة','hero.title1':'مصنوع','hero.title2':'عشان تشتهيه','hero.copy':'ثمان طبقات حقيقية. برجر واحد جامد. انزل بالسكرول وشوفه بيتكوّن قدامك.','hero.scroll':'انزل',
 'pack.kicker':'الكومبو الكامل','pack.title1':'متجهز','pack.title2':'بإتقان','pack.copy':'طازة، متغلف صح، وجاهز ليك.','pack.cta':'كوّن أوردرِك','pack.ready':'جاهز','pack.closed':'متغلف. مقفول. RiWebs.',
 'home.signature':'برجراتنا المميزة','home.choose':'اختار بطل\nأوردرِك.','home.view':'شوف كل البرجر →','home.lane':'اختار اللي نفسك فيه','home.more':'أكتر من\nاختيار.','home.explore':'شوف المنيو كامل →','home.manifestoTag':'RIWEBS / أكل حلو / وقت أحلى','home.manifesto':'البرجر اللي\nهتفضل فاكره\nوإنت راجع البيت.','home.exploreCard':'استكشف',
 'cat.burgers':'برجر','cat.sandwiches':'ساندوتشات','cat.sides':'سايدز','cat.drinks':'مشروبات','cat.burgersCopy':'طبقات كبيرة وطعم أكبر.','cat.sandwichesCopy':'امسكه. خد قضمة. وكرر.','cat.sidesCopy':'الإضافات هنا أساسية.','cat.drinksCopy':'بارد لحد آخر قضمة.',
 'page.menu.kicker':'المنيو كامل','page.menu.title':'اختار اللي نفسك فيه.','page.menu.copy':'برجرات، وجبات كاملة، سايدز مقرمشة، مشروبات باردة وصوصات تكمل الأوردر.',
 'page.burgers.kicker':'برجراتنا','page.burgers.title':'طبقات معمولة بقصد.','page.burgers.copy':'كل برجر متوازن بين الخبز المحمص، الخضار الطازة، الحشوة والصوص المميز.',
 'page.sandwiches.kicker':'الساندوتشات','page.sandwiches.title':'سهل تمسكه. صعب تسيبه.','page.sandwiches.copy':'ساندوتشات RiWebs بطبقات وصوصات مختلفة لكل مزاج.',
 'page.sides.kicker':'السايدز والصوصات','page.sides.title':'الإضافات ليها مكانها.','page.sides.copy':'بطاطس، كول سلو، كاتشب، رانش، مايونيز، مستردة وباربكيو.',
 'page.drinks.kicker':'المشروبات','page.drinks.title':'برد على آخر قضمة.','page.drinks.copy':'مشروبات غازية وطاقة، مع اختيار النكهة لما تكون متاحة.',
 'page.about.kicker':'حكايتنا','page.about.title':'براند برجر له شخصيته.','page.about.copy':'فكرة RiWebs بسيطة: الأكل المعروف يقدر يفضل مألوف وفي نفس الوقت يبقى متصمم ومميز ويستاهل الحماس.','about.why':'ليه RiWebs','about.head':'أكل حلو.\nتصميم حلو.\nمن غير اختصارات.','about.copy':'من البرجر للتغليف، كل تفصيلة ليها نفس الهوية: ألوان دافية، شهية كبيرة وتفاصيل نظيفة.','about.v1':'القرمشة أولًا','about.v1c':'الملمس مهم زي الطعم.','about.v2':'يتعمل طازة','about.v2c':'كل طبقة ليها سبب.','about.v3':'خليه RiWebs','about.v3c':'تجربة مميزة من أول البوكس لآخر قضمة.',
 'page.contact.kicker':'تواصل معنا','page.contact.title':'تعالى وإنت جعان.','page.contact.copy':'عندك سؤال أو رأي أو محتار تختار إيه؟ RiWebs موجود.','contact.location':'الموقع','contact.hours':'مواعيد العمل','contact.daily':'يوميًا','contact.city':'القاهرة','contact.country':'مصر','contact.instagram':'إنستجرام','contact.facebook':'فيسبوك','contact.tiktok':'تيك توك','contact.visit':'زيارة','contact.map':'مطعم RIWEBS','contact.maploc':'القاهرة، مصر',
 'cart.title':'أوردرِك','cart.cart':'السلة','cart.empty':'السلة مستنية حاجة لذيذة.','cart.total':'الإجمالي','cart.confirm':'تأكيد الأوردر على واتساب','cart.note':'كل المنتجات والكميات والاختيارات هتتبعت تلقائيًا لـ RiWebs على واتساب للتأكيد.','cart.clear':'مسح الأوردر','cart.standard':'عادي',
 'custom.size':'الحجم','custom.type':'النوع / النكهة','custom.extras':'إضافات','custom.add':'إضافة للأوردر','card.from':'يبدأ من','filter.all':'الكل','filter.burgers':'برجر','filter.sandwiches':'ساندوتشات','filter.meals':'وجبات','filter.sides':'سايدز','filter.drinks':'مشروبات','filter.sauces':'صوصات',
 'footer.tag':'برجر وبطاطس ووقت حلو — بتفاصيل معمولة صح.','footer.explore':'استكشف','footer.visit':'زورنا','footer.follow':'تابعنا · زيارة','footer.daily':'يوميًا','footer.menu':'المنيو','footer.burgers':'البرجر','footer.sides':'السايدز والصوصات','footer.drinks':'المشروبات','footer.privacy':'الخصوصية','footer.terms':'الشروط','footer.order':'اطلب من RIWEBS',
};

const namesAr:Record<string,string>={
 'classic-burger':'كلاسيك برجر','double-burger':'دابل برجر','crispy-burger':'كريسبي برجر','beef-burger':'بيف برجر','double-beef':'دابل بيف برجر','chicken-roll':'تشيكن رول','beef-roll':'بيف رول','classic-sandwich':'كلاسيك ساندوتش','complete-meal':'وجبة كاملة','golden-fries':'بطاطس جولدن','coleslaw':'كول سلو','pepsi':'بيبسي','mirinda':'ميرندا','sprite':'سبرايت','7up':'سفن أب','redbull':'ريد بول','vseven':'V7','ketchup':'كاتشب','ranch':'صوص رانش','mayonnaise':'مايونيز','mustard':'مستردة','bbq':'صوص باربكيو'};
const descAr:Record<string,string>={
 'classic-burger':'برجر طري مع خس وطماطم وشيدر وصوص RiWebs.','double-burger':'طبقتين كبار مع جبنة وصوص مميز.','crispy-burger':'تشيكن كريسبي ذهبي مع جبنة وخضار وصوص قوي.','beef-burger':'لحم مشوي وشيدر وخضار طازة في خبز محمص.','double-beef':'دابل بيف تقيل للشهية الكبيرة.','chicken-roll':'رول تشيكن كريسبي مع خس وصوص كريمي.','beef-roll':'رول بيف مع جبنة وخضار وصوص مميز.','classic-sandwich':'اختيار بسيط ومتوازن وصوصه مظبوط.','complete-meal':'برجر وبطاطس وكول سلو ومشروب في بوكس كامل.','golden-fries':'بطاطس مقرمشة وساخنة ومتتبلة خفيف.','coleslaw':'كول سلو بارد وكريمي ومقرمش.','pepsi':'بيبسي ساقع.','mirinda':'ميرندا برتقال ساقع.','sprite':'سبرايت ليمون ساقع.','7up':'سفن أب ليمون ساقع.','redbull':'اختار إصدار أو نكهة ريد بول اللي تحبها.','vseven':'اختار واحدة من خمس نكهات V7.','ketchup':'كاتشب طماطم كلاسيك.','ranch':'رانش كريمي بارد.','mayonnaise':'مايونيز كريمي.','mustard':'مستردة بطعم مميز.','bbq':'باربكيو مدخن وحلو.'};
const choiceAr:Record<string,string>={
 'Single':'سنجل','Double':'دابل','Triple':'تريبل','Regular':'عادي','Large':'كبير','Extra cheese':'جبنة زيادة','Extra patty':'قطعة لحم زيادة','Jalapeño':'هالبينو','House sauce':'صوص RiWebs','Extra chicken/beef':'حشوة زيادة','Original':'أوريجينال','Sugarfree':'بدون سكر','Zero':'زيرو','White Peach':'خوخ أبيض','Cherry & Wild Berries':'كرز وتوت بري','Coconut & Berry':'جوز هند وتوت','Açaí Berry':'أساي بيري','Watermelon':'بطيخ','Tropical':'تروبيكال','Blueberry':'توت أزرق','Pink Lemonade':'بينك ليمونيد','Pomegranate':'رمان','Lemon Mint':'ليمون نعناع','Piña Colada':'بينا كولادا','Beef':'بيف','Crispy chicken':'تشيكن كريسبي','Spicy':'سبايسي','Classic':'كلاسيك','Smoky BBQ':'باربكيو مدخن','BBQ':'باربكيو','Chicken':'تشيكن','Classic burger':'كلاسيك برجر','Crispy burger':'كريسبي برجر','Beef burger':'بيف برجر','Extra fries':'بطاطس زيادة','Extra coleslaw':'كول سلو زيادة','Extra sauce':'صوص زيادة','Cheese sauce':'صوص جبنة','330 ml':'330 مل','500 ml':'500 مل'};
const categoryAr:Record<string,string>={'Burgers':'برجر','Sandwiches':'ساندوتشات','Meals':'وجبات','Sides':'سايدز','Drinks':'مشروبات','Sauces':'صوصات','All':'الكل'};

const C=createContext<Ctx|null>(null);
export function LanguageProvider({children}:{children:React.ReactNode}){
 const [lang,setLangState]=useState<Lang>('en');
 useEffect(()=>{const saved=localStorage.getItem('riwebs-lang') as Lang|null;if(saved==='ar'||saved==='en')setLangState(saved)},[]);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';localStorage.setItem('riwebs-lang',lang)},[lang]);
 const value=useMemo<Ctx>(()=>({lang,setLang:setLangState,t:(k)=>((lang==='ar'?ar:en)[k]??en[k]??k),itemName:(item)=>lang==='ar'?(namesAr[item.id]||item.name):item.name,itemDescription:(item)=>lang==='ar'?(descAr[item.id]||item.description):item.description,choice:(label)=>lang==='ar'?(choiceAr[label]||label):label,category:(label)=>lang==='ar'?(categoryAr[label]||label):label}),[lang]);
 return <C.Provider value={value}>{children}</C.Provider>
}
export function useLanguage(){const c=useContext(C);if(!c)throw new Error('LanguageProvider missing');return c}
